config/routes.rb
Rails.application.routes.draw do
  get 'home' => 'static_pages#home', :as => 'home'
  get 'contacts' => 'static_pages#contacts', :as => 'contacts'
  get 'about' => 'static_pages#about', :as => 'about'
  get 'order' => 'static_pages#order', :as => '_order'
  get 'userslist' => 'static_pages#userslist', :as => 'userslist'
  get 'privatpolicy' => 'static_pages#privatpolicy', :as => 'privatpolicy'
  get 'sitetopic' => 'static_pages#sitetopic', :as => 'sitetopic'
  get 'adminpanel' => 'static_pages#adminpanel', :as => 'adminpanel'
  get "sitemap.xml" => "static_pages#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "static_pages#robots", format: :text, as: :robots
  get 'facebook' => 'static_pages#facebook', :as => 'facebook'
  get 'vkontakte' => 'static_pages#vkontakte', :as => 'vkontakte'

  devise_for :users, :controllers => { registrations: 'registrations',
                                       omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions' }
  resources :users

  match 'remote_sign_up', to: 'remote_content#remote_sign_up', via: [:get]
  match 'remote_sign_in', to: 'remote_content#remote_sign_in', via: [:get]

  match '/users/:id/finish_signup' => 'users#finish_signup',
        via: [:get, :patch], as: :finish_signup

  resources :categories do
    member do
      get :session_update
      post :temp_update
      patch :temp_update
    end
  end

  devise_scope :user do
    get "sign_out", to: "devise/sessions#destroy"
  end

  root 'static_pages#home'

end

app/controllers/application_controller.rb
#   class ApplicationController
#   Copyright (c) 2015-2016, Sergy Nazarevich.
#   This file is licensed under the Common Domain General Public License.

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include HttpAcceptLanguage::AutoLocale
  before_filter :store_request_in_thread
  before_action :set_locale
  before_action :set_session
  protect_from_forgery with: :exception
  helper_method :logged_in?

  def set_locale
    I18n.locale = I18n.default_locale
    http_accept_language.compatible_language_from(I18n.available_locales) && I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
    params[:locale] && I18n.locale = params[:locale]
  end

  def set_session
    @user = User.find(current_user.id) if current_user
    !session['temporary'] && session['temporary'] = ((defined? @user) && !@user.temporary.blank? && @user.temporary) || SecureRandom.uuid
    session['history'].blank? && (session['history'] = false)
    (!session['category'] || session['category'].blank?) && (session['category'] = 3)
    (!session['view'] || session['view'].blank?) && (session['view'] = 'showcase')
    (!session['deffered'] || session['deffered'].blank?) && (session['deffered'] = Array.new)
    if current_user
      @user.temporary = session['temporary'] if (@user.temporary.blank? || @user.temporary != session['temporary'])
      @user.update(params[:temporary])
    end
  end

  def logged_in?
    session[:token].present?
  end

  def require_admin
    (!current_user || !current_user.is_admin) && (redirect_to root_path, :error => 'You are not admin!')
  end

  #def default_url_options(options={})
  #  { :locale => I18n.locale }
  #end

  def store_request_in_thread
    Thread.current[:request] = request.host_with_port
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def flash_normal
    render 'messages'
  end

  def show_flash
    f = ""
    f += "<div class=\"alert alert-success\">#{notice}</div>" if notice
    f += "<div class=\"alert alert-error\">#{alert}</div>" if alert
    f.html_safe
  end

  def bootstrap_icon_link_to (text, url, icon, html_options = {})
    link_to url, html_options do
      "<i class=\"#{icon}\"></i> #{text}".html_safe
    end
  end

  def sort_link_to (text, query, url, html_options = {})
    if defined? descA[query]
      desc_q = true
      icon = '.glyphicon-arrow-down'
    else
      desc_q = false
      icon = '.glyphicon-arrow-up'
    end
    url = url + "/?sort='#{query}'&desc='#{desc_q}'"
    link_to url, html_options do
      "#{text} <i class='.glyphicon #{icon}></i>".html_safe
    end
  end
end

app/views/application/_about.html.haml
= content_for :custom_meta_tags do
  %link{rel: "canonical", href: "#{request.original_url}"}
  %meta{property: "og:image", content: "http://mirmarbi.com/bannerShare.jpg"}
  %meta{property: "og:image:type", content: "image/jpeg"}
  %meta{property: "og:image:width", content: "487"}
  %meta{property: "og:image:height", content: "249"}
  - keywords = ['marbi', 'mirmarbi']
  - keywords << ['turkey', 'турция', 'турція', 'турецкие', 'турецькі', 'turkish']
  %meta{name: "keywords", content: "#{keywords.join(', ')}"}
.container.hero
  .page-title
    %h1.headline
      =t(:_about)
    %h2.subheadline
      =t('about.p4')
    .col-sm-8
      .heading.text-left.col-sm-8.col-sm-offset-2.wow.fadeInUp.animated{ 'data-wow-duration' => "1500ms", 'data-wow-delay' => "500ms"}
        %h2
  %video.sohpVid{autoplay: "", loop: "", poster: "//cdn.mirmarbi.com/mm3aboutjpeg.jpeg"}
    %source{src: "//cdn.mirmarbi.com/mm3con.mp4", type: "video/mp4"}

app/views/application/_admin_menu.html.haml
%ul{class: ['nav', 'adminbar-nav']}
  %li{class: ['direct', 'btn-nav-dashboard', 'active']}
    %a{href: "#{adminpanel_path}", class: 'gradient'}
      %i{class: [ 'fa', 'fa-dashboard']}
      =t('activerecord.models.dashboard')
  %li{class: ['direct', 'btn-nav-user', 'btn-nav-catalog']}
    %a{href: "#{users_path}"}
      %i{class: [ 'fa', 'fa-user']}
      =t('activerecord.models.user')
  %li{class: ['direct', 'btn-nav-category']}
    %a{href: "#{categories_path}"}
      %i{class: [ 'fa', 'fa-bars']}
      =t('activerecord.models.category')
  %li{class: ['direct', 'btn-nav-product']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-book']}
      =t('activerecord.models.product')
  %li{class: ['direct', 'btn-nav-gallery']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-picture-o']}
      =t('activerecord.models.gallery')
  %li{class: ['direct', 'btn-nav-product_code']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-sticky-note']}
      =t('activerecord.models.product_code')
  %li{class: ['direct', 'btn-nav-payment_type']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-credit-card-alt']}
      =t('activerecord.models.payment_type')
  %li{class: ['direct', 'btn-nav-order']}
    %a{href: "#product"}
      %i{class: [ 'fa', 'fa-briefcase']}
      =t('activerecord.models.order')

app/views/application/_admin_panel_controlls.html.haml
.controlls

app/views/application/_contact.html.haml
= content_for :custom_meta_tags do
  %link{rel: "canonical", href: "#{request.original_url}"}
  %meta{property: "og:image", content: "http://mirmarbi.com/bannerShare.jpg"}
  %meta{property: "og:image:type", content: "image/jpeg"}
  %meta{property: "og:image:width", content: "487"}
  %meta{property: "og:image:height", content: "249"}
  - keywords = ['marbi', 'mirmarbi']
  - keywords << ['turkey', 'турция', 'турція', 'турецкие', 'турецькі', 'turkish']
  %meta{name: "keywords", content: "#{keywords.join(', ')}"}
.container.hero
  .page-title
    %h1.headline
      =t(:_contact_us)
    %h2.subheadline
      =t('contactus.desc')
    .contact-form.wow.fadeIn.animated{ 'data-wow-duration' => "2000ms", 'data-wow-delay' => "1000ms"}
      .col-sm-6
        .contact-info.wow.fadeInUp.animated{ 'data-wow-duration' => "2000ms", 'data-wow-delay' => "800ms"}
          %ul.address
            %li
              %i.glyphicon.glyphicon-earphone
              %span
                Phone:
                +38-XXX-XXX-XXXX
            %br
            %li
              %i.glyphicon.glyphicon-envelope
              %span
                Email:
              %a{ href: 'mailto: info@mirmarbi.com'}
                info@mirmarbi.com
  %video.sohpVid{autoplay: "", loop: "", poster: "//cdn.mirmarbi.com/mm3conjpeg.jpg"}
    %source{src: "//cdn.mirmarbi.com/mm3con.mp4", type: "video/mp4"}

app/views/application/_footer.html.haml
%section
  .col-sm-3
    %a{href: './privatpolicy'}
      Privacy Policy
    %br
    %a{href: "#sitetopic"}
      = t(:_topic)
  .powered
    %p
      Rails #{Rails.version} | Env #{Rails.env}
  .copyright
    %p
      \&copy; #{Time.now.year}
      %span.pink 
        Mir Marbi
      All Rights Reserved

app/views/application/_lang.html.haml
.lang_panel
  - langA = ['uk', 'ru', 'en', 'be', 'tr', 'pl' ]
  - req = request.fullpath
  - langA.each do |lang|
    - lang == 'uk' && ((flag = 'ua') && (title = "українською"))
    - lang == 'ru' && ((flag = 'ru') && (title = "по-русски"))
    - lang == 'en' && ((flag = 'us') && (title = "for english"))
    - lang == 'tr' && ((flag = 'tr') && (title = "türkçe"))
    - lang == 'pl' && ((flag = 'pl') && (title = "w języku polskim"))
    - lang == 'be' && ((flag = 'by') && (title = "па беларуску"))
    %a{href: "http://#{lang}.mirmarbi.com/#{req}", class: "flag-icon flag-#{lang}", title: "#{title}", alt: "#{title}"}
      %img{src: "/flags/#{flag}.png"}

app/views/application/_leftpanel.html.haml
#social
  .contact-btn
    %a.btn.btn-primary.btn-contact.scroll{ href: '#contact'}
      %i.glyphicon.glyphicon-edit
      =t(:_contact_us)
      .insert

app/views/application/_menu.html.haml
%ul{class: ['nav', 'navbar-nav', 'navbar-right']}
  %li{class: ['direct', 'active']}
    = bootstrap_icon_link_to t(:_home), root_path, 'fa fa-home'
  %li{class: ['direct', 'btn-nav-catalog']}
    %a{href: "#catalog"}
      %i{class: [ 'fa', 'fa-book']}
      =t(:_catalog)
  %li{class: ['direct', 'btn-nav-contacts']}
    %a{href: "#{contacts_path}", class: 'gradient'}
      %i{class: [ 'fa', 'fa-pencil-square-o']}
      =t(:_contact_us)
  %li{class: ['direct', 'btn-nav-about']}
    %a{href: "#{about_path}", class: 'gradient'}
      %i{class: [ 'fa', 'fa-info-circle']}
      =t(:_about)
  %li{class: ['direct', 'btn-abs-cart']}
    %a{href: "#order", class: 'button btn'}
      %i{class: [ 'glyphicon', 'glyphicon-shopping-cart']}
      .inner
        %span.item
          0 item
        %br
        %span.value
          0 $
  - if current_user
    %li{class: ['remote-modal']}
      %a{href: '/sign_out', class: 'gradient'}
        %i{class: [ 'fa', 'fa-sign-out']}
        = t('layouts.header.logout')
    - if current_user.is_admin
      %li{class: ['remote-modal', 'btn-nav-adminpanel']}
        %a{href: '/adminpanel', class: 'gradient'}
          %i{class: [ 'fa', 'fa-cogs']}
          Admin panel
    - else
      %li{class: ['direct', 'btn-nav-user', 'remote-modal']}
        = link_to edit_user_password_path(current_user) do
          %i{class: [ 'fa', 'fa-user']}
          =t('account')
  - else
    %li{class: ['remote-modal']}
      = link_to remote_sign_in_path, :remote => true do
        %i{class: [ 'fa', 'fa-sign-in']}
        = t('layouts.header.login')
    %li{class: ['remote-modal']}
      = link_to remote_sign_up_path, :remote => true do
        %i{class: [ 'fa', 'fa-user-plus']}
        = t('registrations.new.sign_up')

app/views/application/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    - type = 'info'
    - msgd = msg.downcase
    - msgd['success'] && type = 'success'
    - ( msgd['error'] || msgd['fail'] || msgd['invalid'] ) && type= 'danger'
    %div{:class => "alert alert-#{type}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_selltype.html.haml
.selltype_panel
  %ul.selltype
    %li{class: ['direct', 'active']}
      %a{href: "#opt"}
        %i{class: [ 'fa', 'fa-truck']}
        опт
    %li{class: ['direct']}
      %a{href: "#roz"}
        %i{class: [ 'fa', 'fa-cart-arrow-down']}
        розница